name: health_app_repo
description: App to exercise Health and Geofencing

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_geofence: ^0.4.1
  activity_recognition_flutter: ^4.0.0
  geolocator: ^7.0.3
  flutter_local_notifications: ^5.0.0+4
  ansicolor: ^2.0.1
  logging: ^1.0.1
  logging_appenders: ^1.0.0
  simple_logger: ^1.8.0+1
  google_maps_flutter: ^2.0.4
  dio: ^4.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  responsive_builder: ^0.4.1
  shared_preferences: ^2.0.5
  intl: ^0.17.0
  http: ^0.13.3
  uuid: ^3.0.4
  flutter_dotenv: ^4.0.0-nullsafety.0
  google_fonts: ^2.0.0
  connectivity: ^3.0.3
  permission_handler: ^7.1.0
  page_transition: ^2.0.1-nullsafety.0
  health: ^3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

